server:
    port: 7777
    contextPath: /cron
logging:
    level:
        org.springframework: DEBUG
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/cron-system?useUnicode=true&characterEncoding=UTF-8
        host: 127.0.0.1
        port: 3306
        dbname: cron-system
        username: root
        password: 123456
